---
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Jovan42/cloud-config-tut
          search-paths:
            - 'station*'
server:
  port: 8888
